README.md

docs(README): Basic setting

---

toronto/src/components/atoms/Text/Text.css
toronto/src/components/atoms/Text/index.js
toronto/src/stories/components/atoms/Text.stories.js

[Components/Atoms] Text 기능 구현

---

toronto/src/components/atoms/Loader/LoaderList.js
toronto/src/components/atoms/Loader/index.js
toronto/src/stories/components/atoms/Loader.stories.js

Loader 컴포넌트를 만들었습니다.
몇 가지 로딩 컴포넌트를 만들었습니다. 
6가지 타입의 로더가 있습니다. 
- spinner
- spinners
- three-dots
- puff
- spinning-circles
- audio
size: 로더의 가로, 세로 길이
color: 로더 색상
loading: 현재 로딩중인지
type: 6가지 타입, 문자열
임의로 추가해 봤는데 혹시 추가하고 싶은 로더 있으면 말씀해주세요!

[Components/Atoms] Loader 컴포넌트 구현

---

toronto/.prettierrc
toronto/src/components/atoms/Button/index.js
toronto/src/components/atoms/Spacer/index.js
toronto/src/stories/components/atoms/Button.stories.js
toronto/src/stories/components/atoms/Divider.stories.js
toronto/src/stories/components/atoms/Input.stories.js
toronto/src/stories/components/atoms/Spacer.stories.js
toronto/src/stories/components/atoms/Text.stories.js

- Button 컴포넌트 구현
- Spacer 컴포넌트 구현
- Prettier 적용해뒀습니다!
- Button
Button을  여러개로 추상화하여 구현하고 싶었는데 아직까지 기능이 전부 구현되지 않았습니다. 열심히 추가해보도록 하겠습니다. 지금 당장은 버튼이 필요하여 먼저 merge 후 추가 기능은 branch 살려두고 나중에 개발하여 다른 PR에 올리겠습니다. 
아이콘, 로딩 같은 경우 다른 컴포넌트가 필요하여 개발이 안된 상태입니다.
-Spacer
강의에서 개발한 것 그대로 가지고 왔습니다. 주의사항이 있습니다. div 태그가 아닌 경우 작동을 안하는 것처럼 보이는데 <div>로 감싸주게되면 동작합니다.
- Prettier 적용했습니다. 확인부탁드려요~!

[Components/Atoms] Button, Spacer 컴포넌트 구현

---

toronto/.prettierrc
toronto/craco.config.js
toronto/src/App.js
toronto/src/components/atoms/Button/index.js
toronto/src/components/atoms/Card/index.js
toronto/src/components/atoms/Skeleton/Base.jsx
toronto/src/components/atoms/Skeleton/Box.jsx
toronto/src/components/atoms/Skeleton/Circle.jsx
toronto/src/components/atoms/Skeleton/Paragraph.jsx
toronto/src/components/atoms/Skeleton/index.js
toronto/src/components/atoms/Spacer/index.js
toronto/src/components/atoms/StyledLink/index.js
toronto/src/pages/NotFound.jsx
toronto/src/pages/index.js
toronto/src/stories/components/atoms/Button.stories.js
toronto/src/stories/components/atoms/Card.stories.js
toronto/src/stories/components/atoms/Divider.stories.js
toronto/src/stories/components/atoms/Input.stories.js
toronto/src/stories/components/atoms/Skeleton.stories.js
toronto/src/stories/components/atoms/Spacer.stories.js
toronto/src/stories/components/atoms/Text.stories.js

강의 내용과 거의 똑같이 Skeleton 컴포넌트를 만들었습니다.
- Box
`width`와 `height`를 설정할 수 있습니다.
- Circle
`size` 를 설정할 수 있습니다. 
- Paragraph
`line` 으로 줄의 개수, `height` 로 각 줄의 높이를 설정할 수 있습니다.
더 멋있는 스켈레톤 없을까 찾아봤는데 결국 못찾았네요ㅠ

[Components/Atoms] Skeleton 컴포넌트 추가 및 스토리 작성

---

toronto/src/components/molecules/PostItem/index.js
toronto/src/stories/components/molecules/PostItem.stories.js

`PostItem` 컴포넌트 링크 처리 및 좋아요/좋아요 취소 기능 구현
<br>
**Default**
<br><br>
**ContentOverflow**
<br><br>
**PostList**
<br>
`react-router`를 이용한 Link 처리는 정상적으로 동작하는 것을 확인했으며, 좋아요 및 좋아요 취소 기능도 모두 구현되어 있습니다.
`button`은 일단 `StyledButton` 컴포넌트를 생성해서 구현하였으며, `API` 연동 기능도 더미 데이터를 통해 정상적으로 동작하는 것을 확인했습니다.
추후 `UserId` 관련해서 `Context API`로 변경해야 하며, `API `요청 함수(fetch로 구현되어 있는 부분)도 수정한 뒤 다시 반영해야 되기 때문에 현재 PR에 큰 문제가 없다면 빠르게 merge한 뒤에 나중에 한번에 수정해도 좋을 것 같습니다!

[Components/Molecules] PostItem 컴포넌트 구현

---

toronto/src/components/molecules/Vote/index.js
toronto/src/stories/components/molecules/Vote.stories.js

결과 페이지에 사용하는 찬성 반대를 선택할 수 있는 Vote 컴포넌트를 만들었습니다.
찬성, 반대를 선택할 수 있고, 상태 변수로 찬성을 선택했는지 반대를 선택했는지 저장합니다. 해당 상태 변수가 변경될 때마다 상위 컴포넌트로부터 전달 받은 함수를 실행합니다. 
- agreeText: 찬성 버튼에 들어갈 텍스트
- disagreeText: 반대 버튼에 들어갈 텍스트
- onChange: 상위 컴포넌트로부터 전달 받는 함수
- 지금은 버튼 컴포넌트에 커스텀 스타일을 적용할 수 없어서 임의로 styled component 를 만들어 사용했습니다. 버튼 컴포넌트에 기능이 추가되면 수정하도록 하겠습니다!

[Components/Molecules] Vote 컴포넌트 추가

---

toronto/.gitignore
toronto/src/components/molecules/PostItem/index.js

기능은 이전과 동일하나, `Token`과 `API END POINT`가 노출되어있는 문제를 수정했습니다.

[Components/Molecules] PostItem의 Token 및 EndPoint 환경변수 처리

---

toronto/src/components/molecules/ControversyVote/index.js
toronto/src/stories/components/molecules/ControversyVote.stories.js

논쟁 페이지에 있는 component 입니다.
- `components/molecules` 랑 색이랑 느낌을 비슷하게 만들려고 하였습니다.
- 각 img위의 title을 변경가능합니다.
- 같은 img를 사용합니다.(img 변경가능)
- button click 시 색으로 표시가능 합니다.

[Components/molecules]: ControversyVote 기능 구현

---

toronto/src/components/molecules/UserItem/index.js
toronto/src/stories/components/molecules/UserItem.stories.js

`UserListPage`에 필요한 `UserItem` 컴포넌트 구현
- user: `user` 객체
기존에 사용하던 `PostItem`과 기능적으로는 큰 차이가 없습니다. 한 분이라도 코드 확인하시면 바로 merge해도 무방할 것 같습니다!

[Components/Molecules] UserItem 컴포넌트 구현

---

toronto/src/components/atoms/index.js
toronto/src/components/molecules/Tooltip/index.js
toronto/src/components/molecules/index.js
toronto/src/components/organisms/NavigationBar/index.js
toronto/src/components/organisms/index.js
toronto/src/layout/Layout.jsx
toronto/src/stories/components/molecules/Tooltip.stories.js

NavigationBar 컴포넌트와 해당 컴포넌트에서 사용할 Tooltip 컴포넌트를 만들었습니다.
https://user-images.githubusercontent.com/61747121/174427899-da25c56b-6fe9-4980-a2bd-805a059aa0ae.mov
로그인 되어 있지 않을 때에는 `로그인`, `회원가입` 두 가지 기능을 제공하고
로그인 되어 있을 때에는 사용자 정보 보기, 로그아웃, 내 정보 보기 기능을 제공합니다.
로고를 누르면 홈으로 이동합니다.
아이콘으로만 되어 있는 링크도 있다보니 어떤 역할을 하는지 모를 수 있을 것 같아서 `Tooltip` 컴포넌트를 추가로 만들었습니다.
`<Tooltip></Tooltip>` 으로 툴팁 적용을 원하는 컴포넌트를 감싸고, text prop으로 툴팁 메시지를 설정할 수 있습니다.
`NavigationBar` 컴포넌트는 라우팅 기능이 있어서 스토리 파일을 만들지 않았습니다.
- NavigationBar 와 Tooltip 을 구분해야 하는데 그냥 만들어 버렸네요...
- 코드에 inline-style 을 많이 사용했는데 리팩토링 하도록 하겠습니다.
- 아직은 없는 링크가 있어서 임시로 홈으로 이동하도록 해뒀는데 링크 추가되면 변경하도록 하겠습니다.
- NavigationBar 에서 직접 전역의 user 데이터에 접근할 수 있는데, 컴포넌트가 해도 되는 일일까 싶어서 layout 에서 내려 받는 방법으로 구현했습니다!

[Components] NavigationBar(Organisms) / Tooltip(Molecules) 컴포넌트 구현

---

toronto/src/components/molecules/index.js
toronto/src/pages/Post.jsx

글쓰기 페이지 `custom title` 변경, 유저 토큰 사용 기능을 추가했습니다.
글쓰기 페이지 `custom title` 변경, 유저 토큰 사용 기능을 추가했습니다. 기존과 변경된 사항은 거의 없습니다!

[Pages/CreatePostPage] 글쓰기 페이지 변경

---

toronto/src/api/Api.js
toronto/src/components/molecules/Vote/index.js
toronto/src/pages/ControversyResult.jsx

결과 페이지를 리팩토링 했습니다.
- 포스트 삭제 기능 추가
- 투표 결과 퍼센트 출력
- 댓글 의견 설정하는 Vote 컴포넌트에서 불필요한 텍스트 삭제
- axios 관련 함수 `api` 폴더 내에 만들고 가져와서 사용하는 방식으로 수정
```javascript
const checkAuthUser = useCallback(() => {
if (!userData?.user?.loading && !userData?.user?.data) {
alert('로그인 된 사용자만 접근할 수 있습니다.');
navigate('/');
}
}, [userData, navigate]);
useEffect(() => {
checkAuthUser();
checkValidPost();
getPostData();
}, [getPostData, checkValidPost, checkAuthUser]);
```
인가 된 사용자 확인하는 부분은 아직 확정되지 않아서 임의로 전역 초기 상태 수정하고 loading 값과 user data 값으로 처리하도록 했습니다. 이 부분은 확정되면 다시 수정할 것 같습니다.

[Refactor] ResultPage 리팩토링

---

toronto/src/api/Api.js
toronto/src/pages/Post.jsx

글쓰기 페이지를 리팩토링 했습니다.
보여지는 기능은 같고, `api` 폴더 내의 함수로 만들어 사용하도록 했습니다. 로그인 된 사용자인지 확인하도록 했는데 이 부분은 정해지면 다시 수정하도록 하겠습니다

[Refactor] CreatePostPage 리팩토링

---

toronto/src/components/molecules/Tooltip/index.js

툴팁 컴포넌트를 리팩토링 했습니다.
기능은 같고, styled-components 를 사용하도록 수정했습니다. 화면 밖으로 툴팁이 나갈 때 안으로 들어오도록 하고 싶었는데 실패해서 그건 일단 나중에 다시 보도록 하겠습니다.

[Refactor] Tooltip 컴포넌트 리팩토링

---

toronto/src/components/molecules/Upload/UploadArea.jsx
toronto/src/components/molecules/Upload/index.js

Upload와 UploadArea 컴포넌트를 리팩토링 했습니다.
import 방법을 통일하고, `children` 의 `prop type`을 `function` 또는 `node` 로 받도록 수정했습니다.

[Refactor] Upload 컴포넌트 리팩토링

---

toronto/src/components/organisms/CommentList/index.js

CommentList 컴포넌트를 리팩토링 했습니다.
import 방법을 변경했습니다.

[Refactor] CommentList 컴포넌트 리팩토링

---

toronto/src/api/Api.js

`Api.js` 의 변경 사항을 머지하는 과정에서 웹 에디터로 충돌을 해결했는데 그 때 실수로 코드를 날려버렸네요. 다시 수정했습니다!

[Fix] 잘못된 머지 수정

---

toronto/src/api/Api.js
toronto/src/pages/Home.jsx

`API` 요청 로직들을 `Api.js`에 함수로 분리했습니다.

[Pages/Home] 홈페이지 API 요청 리팩토링

---

toronto/src/components/molecules/CommentItem/index.js
toronto/src/components/organisms/CommentList/index.js
toronto/src/layout/Layout.jsx
toronto/src/pages/ControversyResult.jsx

[Style/ControversyResult] 투표 결과 페이지 전반적인 디자인 수정

---

toronto/src/pages/UserProfile.jsx

네트워크 상황이 좋지 않을 경우 유저 프로필의 게시물 탭에서 스켈레톤 컴포넌트가 보이도록 했습니다.

[Refactor/UserProfile] 유저 프로필 게시물 스켈레톤 처리 추가
